# .gitlab-ci.yml
stages:
  - deploy

pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add rsync
  script:
    - mkdir -p public
    - rsync -av --exclude='public' --exclude='.git' ./* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH